/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package proyectocompiladores;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

class Token {
        Token (int numToken, String token, String tipo, int linea){
        this.numToken = numToken;	
        this.token = new String(token);
        this.tipo = tipo;
        this.linea = linea;
       
    }
 public int numToken;
    public String token;
    public String tipo;
    public int linea;

    public String toString() {
    
		return token+" : "+tipo+ " linea :    "+(linea+1) +",";	
    }
}

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>C:/Users/USER/Documents/NetBeansProjects/PROYECTOcOMPILADORES/src/proyectocompiladores/Lexico.flex</tt>
 */
public class Lexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\3\1\55\1\55\1\4\22\0\1\2\1\52\2\0\1\51"+
    "\1\0\1\54\1\5\1\44\1\45\1\21\1\47\1\51\1\11\1\50"+
    "\1\22\1\17\10\1\1\20\1\51\1\51\1\52\1\53\1\52\2\0"+
    "\1\14\30\6\1\15\1\7\1\0\1\16\3\0\1\10\1\31\1\32"+
    "\1\41\1\37\1\26\1\36\1\33\1\23\2\46\1\27\1\46\1\24"+
    "\1\30\1\42\1\46\1\34\1\35\1\25\1\43\1\46\1\40\2\46"+
    "\1\12\1\51\1\13\1\51\7\0\1\55\u1fa2\0\1\55\1\55\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\1\1\4\1\5\1\6"+
    "\1\5\1\1\2\5\13\6\1\5\1\1\2\5\4\0"+
    "\1\2\1\7\1\0\1\3\1\6\1\10\13\6\1\0"+
    "\1\11\1\7\1\12\1\3\14\6\1\0\1\6\1\13"+
    "\2\6\1\0\1\6\24\0\1\14";

  private static int [] zzUnpackAction() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\56\0\212\0\270\0\346\0\56"+
    "\0\u0114\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256"+
    "\0\u0284\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398\0\u03c6"+
    "\0\u03f4\0\u0422\0\u0450\0\u047e\0\u04ac\0\u019e\0\u0422\0\u04da"+
    "\0\u0142\0\u04ac\0\u0508\0\u0508\0\u0536\0\u0114\0\u0564\0\u0592"+
    "\0\u05c0\0\u05ee\0\u061c\0\u064a\0\u0678\0\u06a6\0\u06d4\0\u0702"+
    "\0\u0730\0\u075e\0\u0422\0\56\0\56\0\u078c\0\u07ba\0\u07e8"+
    "\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958"+
    "\0\u0986\0\u09b4\0\u09e2\0\u0a10\0\u0114\0\u0a3e\0\u0a6c\0\u0a9a"+
    "\0\u0ac8\0\u0af6\0\u0b24\0\u0b52\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a"+
    "\0\u0c38\0\u0c66\0\u0c94\0\u0cc2\0\u0cf0\0\u0d1e\0\u0d4c\0\u0d7a"+
    "\0\u0da8\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\56";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\11\1\13\2\7\1\10\2\3\1\14\1\15"+
    "\1\16\1\11\1\17\1\20\1\11\1\21\1\22\1\23"+
    "\1\11\1\24\1\25\1\11\1\26\1\27\1\30\2\11"+
    "\1\31\1\10\1\11\1\12\1\32\1\10\2\33\1\34"+
    "\60\0\1\3\4\0\1\35\1\0\1\35\1\0\4\35"+
    "\1\0\2\3\1\36\1\0\21\35\2\0\1\35\1\0"+
    "\1\37\10\0\1\4\60\0\1\40\1\0\1\40\1\0"+
    "\4\40\5\0\21\40\2\0\1\40\10\0\1\7\4\0"+
    "\1\7\1\0\1\7\1\0\4\7\1\0\2\7\1\36"+
    "\1\0\21\7\2\0\1\7\10\0\1\11\4\0\1\11"+
    "\1\0\1\11\1\0\4\11\1\0\2\11\1\36\1\0"+
    "\21\11\2\0\1\11\10\0\1\41\15\0\2\41\36\0"+
    "\1\35\4\0\1\35\1\0\1\35\1\0\1\35\1\42"+
    "\2\35\1\0\2\35\1\36\1\0\21\35\2\0\1\35"+
    "\31\0\1\4\54\0\1\43\1\44\34\0\1\11\4\0"+
    "\1\11\1\0\1\11\1\0\4\11\1\0\2\11\1\36"+
    "\1\0\1\11\1\45\1\11\1\46\15\11\2\0\1\11"+
    "\10\0\1\11\4\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\0\2\11\1\36\1\0\10\11\1\47\1\50\7\11"+
    "\2\0\1\11\10\0\1\11\4\0\1\11\1\0\1\51"+
    "\1\0\4\11\1\0\2\11\1\36\1\0\4\11\1\52"+
    "\14\11\2\0\1\11\10\0\1\11\4\0\1\11\1\0"+
    "\1\11\1\0\4\11\1\0\2\11\1\36\1\0\20\11"+
    "\1\53\2\0\1\11\10\0\1\11\4\0\1\11\1\0"+
    "\1\11\1\0\4\11\1\0\2\11\1\36\1\0\5\11"+
    "\1\54\13\11\2\0\1\11\10\0\1\11\4\0\1\11"+
    "\1\0\1\11\1\0\4\11\1\0\2\11\1\36\1\0"+
    "\10\11\1\55\10\11\2\0\1\11\10\0\1\11\4\0"+
    "\1\11\1\0\1\11\1\0\4\11\1\0\2\11\1\36"+
    "\1\0\14\11\1\56\4\11\2\0\1\11\10\0\1\11"+
    "\4\0\1\11\1\0\1\11\1\0\4\11\1\0\2\11"+
    "\1\36\1\0\2\11\1\57\16\11\2\0\1\11\10\0"+
    "\1\11\4\0\1\11\1\0\1\11\1\0\4\11\1\0"+
    "\2\11\1\36\1\0\4\11\1\60\14\11\2\0\1\11"+
    "\10\0\1\11\4\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\0\2\11\1\36\1\0\10\11\1\61\10\11\2\0"+
    "\1\11\10\0\1\11\4\0\1\11\1\0\1\11\1\0"+
    "\4\11\1\0\2\11\1\36\1\0\5\11\1\46\13\11"+
    "\2\0\1\11\16\0\1\62\47\0\1\63\15\0\2\63"+
    "\110\0\1\64\56\0\1\64\2\0\1\35\4\0\1\35"+
    "\1\0\1\35\1\0\4\35\1\0\2\35\1\36\1\0"+
    "\21\35\2\0\1\35\10\0\1\40\3\0\1\65\1\40"+
    "\1\0\1\40\1\0\4\40\1\0\2\40\2\0\21\40"+
    "\2\0\1\40\15\0\1\66\1\0\1\66\1\0\4\66"+
    "\5\0\21\66\2\0\1\66\10\0\1\11\4\0\1\11"+
    "\1\0\1\11\1\0\4\11\1\0\2\11\1\36\1\0"+
    "\2\11\1\46\14\11\1\67\1\11\2\0\1\11\10\0"+
    "\1\11\4\0\1\11\1\0\1\11\1\0\4\11\1\0"+
    "\2\11\1\36\1\0\14\11\1\70\4\11\2\0\1\11"+
    "\10\0\1\11\4\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\0\2\11\1\36\1\0\20\11\1\71\2\0\1\11"+
    "\10\0\1\11\4\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\0\2\11\1\36\1\0\4\11\1\72\14\11\2\0"+
    "\1\11\10\0\1\11\4\0\1\11\1\0\1\11\1\0"+
    "\4\11\1\0\2\11\1\36\1\0\5\11\1\73\13\11"+
    "\2\0\1\11\10\0\1\11\4\0\1\11\1\0\1\11"+
    "\1\0\4\11\1\0\2\11\1\36\1\0\2\11\1\74"+
    "\16\11\2\0\1\11\10\0\1\11\4\0\1\11\1\0"+
    "\1\11\1\0\4\11\1\0\2\11\1\36\1\0\5\11"+
    "\1\75\13\11\2\0\1\11\10\0\1\11\4\0\1\11"+
    "\1\0\1\76\1\0\4\11\1\0\2\11\1\36\1\0"+
    "\21\11\2\0\1\11\10\0\1\11\4\0\1\11\1\0"+
    "\1\11\1\0\4\11\1\0\2\11\1\36\1\0\2\11"+
    "\1\77\16\11\2\0\1\11\10\0\1\11\4\0\1\11"+
    "\1\0\1\11\1\0\4\11\1\0\2\11\1\36\1\0"+
    "\11\11\1\100\7\11\2\0\1\11\10\0\1\11\4\0"+
    "\1\11\1\0\1\11\1\0\4\11\1\0\2\11\1\36"+
    "\1\0\12\11\1\101\6\11\2\0\1\11\10\0\1\11"+
    "\4\0\1\11\1\0\1\11\1\0\4\11\1\0\2\11"+
    "\1\36\1\0\1\102\20\11\2\0\1\11\17\0\1\103"+
    "\46\0\1\66\4\0\1\66\1\0\1\66\1\0\4\66"+
    "\1\0\2\66\2\0\21\66\2\0\1\66\10\0\1\11"+
    "\4\0\1\11\1\0\1\11\1\0\4\11\1\0\2\11"+
    "\1\36\1\0\20\11\1\104\2\0\1\11\10\0\1\11"+
    "\4\0\1\11\1\0\1\11\1\0\4\11\1\0\2\11"+
    "\1\36\1\0\1\11\1\46\17\11\2\0\1\11\10\0"+
    "\1\11\4\0\1\11\1\0\1\11\1\0\4\11\1\0"+
    "\2\11\1\36\1\0\14\11\1\105\4\11\2\0\1\11"+
    "\10\0\1\11\4\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\0\2\11\1\36\1\0\12\11\1\71\6\11\2\0"+
    "\1\11\10\0\1\11\4\0\1\11\1\0\1\104\1\0"+
    "\4\11\1\0\2\11\1\36\1\0\21\11\2\0\1\11"+
    "\10\0\1\11\4\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\0\2\11\1\36\1\0\17\11\1\67\1\11\2\0"+
    "\1\11\10\0\1\11\4\0\1\11\1\0\1\11\1\0"+
    "\4\11\1\0\2\11\1\36\1\0\4\11\1\46\14\11"+
    "\2\0\1\11\10\0\1\11\4\0\1\11\1\0\1\11"+
    "\1\0\4\11\1\0\2\11\1\36\1\0\11\11\1\46"+
    "\7\11\2\0\1\11\10\0\1\11\4\0\1\11\1\0"+
    "\1\11\1\0\4\11\1\0\2\11\1\36\1\0\20\11"+
    "\1\106\2\0\1\11\10\0\1\11\4\0\1\11\1\0"+
    "\1\11\1\0\4\11\1\0\2\11\1\36\1\0\1\107"+
    "\20\11\2\0\1\11\10\0\1\11\4\0\1\11\1\0"+
    "\1\11\1\0\4\11\1\0\2\11\1\36\1\0\14\11"+
    "\1\46\4\11\2\0\1\11\10\0\1\11\4\0\1\11"+
    "\1\0\1\11\1\0\4\11\1\0\2\11\1\36\1\0"+
    "\4\11\1\101\14\11\2\0\1\11\20\0\1\110\45\0"+
    "\1\11\4\0\1\11\1\0\1\11\1\0\4\11\1\0"+
    "\2\11\1\36\1\0\2\11\1\46\16\11\2\0\1\11"+
    "\10\0\1\11\4\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\0\2\11\1\36\1\0\11\11\1\70\7\11\2\0"+
    "\1\11\10\0\1\11\4\0\1\11\1\0\1\11\1\0"+
    "\4\11\1\0\2\11\1\36\1\0\1\11\1\111\17\11"+
    "\2\0\1\11\21\0\1\112\44\0\1\11\4\0\1\11"+
    "\1\0\1\11\1\0\4\11\1\0\2\11\1\36\1\0"+
    "\13\11\1\46\5\11\2\0\1\11\22\0\1\113\56\0"+
    "\1\114\52\0\1\115\61\0\1\116\56\0\1\117\46\0"+
    "\1\120\56\0\1\121\56\0\1\122\56\0\1\123\56\0"+
    "\1\124\56\0\1\125\52\0\1\126\61\0\1\127\53\0"+
    "\1\130\61\0\1\131\47\0\1\132\64\0\1\133\53\0"+
    "\1\134\60\0\1\135\101\0\1\136\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3726];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\3\1\1\11\24\1\4\0"+
    "\2\1\1\0\16\1\1\0\1\1\2\11\15\1\1\0"+
    "\4\1\1\0\1\1\24\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	
    private int contador;
    private ArrayList<Token> tokens;

	private void Salida() throws IOException{
			String filename = "salida.csv";
			BufferedWriter out = new BufferedWriter(
				new FileWriter(filename));
            System.out.println("\n EXITOSAMENTE GENERADO\n");
			for(Token lexico: this.tokens){
			out.write(lexico + "\n");
			}
			out.close();
	}
public String lexema;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
      contador = 0;
	tokens = new ArrayList<Token>();
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 140) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    	try{
		this.Salida();
        System.exit(0);
	}catch(IOException ioe){
		ioe.printStackTrace();
	}

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { contador++;
   Token lexico = new Token(contador,yytext(),"error_lexico",yyline);
    tokens.add(lexico);
   return lexico;
          }
        case 13: break;
        case 2: 
          { contador++;
Token lexico = new Token(contador,yytext(),"Integer",yyline);
tokens.add(lexico);
return lexico;
          }
        case 14: break;
        case 3: 
          { 
          }
        case 15: break;
        case 4: 
          { contador++;
Token lexico = new Token(contador,yytext(),"ERROR",yyline);
tokens.add(lexico);
return lexico;
          }
        case 16: break;
        case 5: 
          { contador++;
Token lexico = new Token(contador,yytext(),"CaracterEspecial",yyline);
tokens.add(lexico);
return lexico;
          }
        case 17: break;
        case 6: 
          { contador++;
Token lexico = new Token(contador,yytext(),"Identificador",yyline);
tokens.add(lexico);
return lexico;
          }
        case 18: break;
        case 7: 
          { contador++;
Token lexico = new Token(contador,yytext(),"OperadorCompuesto",yyline);
tokens.add(lexico);
return lexico;
          }
        case 19: break;
        case 8: 
          { contador++;
Token lexico = new Token(contador,yytext(),"PalabraReservada",yyline);
tokens.add(lexico);
return lexico;
          }
        case 20: break;
        case 9: 
          { contador++;
Token lexico = new Token(contador,yytext(),"Flotante",yyline);
tokens.add(lexico);
return lexico;
          }
        case 21: break;
        case 10: 
          { contador++;
Token lexico = new Token(contador,yytext(),"Char",yyline);
tokens.add(lexico);
return lexico;
          }
        case 22: break;
        case 11: 
          { contador++;
Token lexico = new Token(contador,yytext(),"Booleano",yyline);
tokens.add(lexico);
return lexico;
          }
        case 23: break;
        case 12: 
          { contador++;
Token lexico = new Token(contador,yytext(),"String",yyline);
tokens.add(lexico);
return lexico;
          }
        case 24: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
