
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 20 16:55:23 COT 2015
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHA = 25;
  public static final int MULT = 7;
  public static final int CHAR = 39;
  public static final int RET = 34;
  public static final int OUTPUT = 33;
  public static final int INPUT = 32;
  public static final int INTEGER = 35;
  public static final int RESTA = 6;
  public static final int INT = 19;
  public static final int FIN = 24;
  public static final int FOR = 20;
  public static final int string = 26;
  public static final int LLAVECERRADA = 11;
  public static final int IDENTIFICADOR = 37;
  public static final int CORCHIZQ = 17;
  public static final int PARENTESISCERRADO = 12;
  public static final int BOOL = 22;
  public static final int DIV = 8;
  public static final int INCREMENTO = 16;
  public static final int SUMA = 5;
  public static final int IF = 27;
  public static final int FLOA = 21;
  public static final int EOF = 0;
  public static final int EQUAL = 13;
  public static final int error = 1;
  public static final int COMA = 2;
  public static final int MENOR = 14;
  public static final int LLAVEABIERTA = 10;
  public static final int MAYOR = 15;
  public static final int CORCHDER = 18;
  public static final int PARENTESISABIERTO = 9;
  public static final int WHILE = 30;
  public static final int THEN = 28;
  public static final int PELSE = 29;
  public static final int DOSP = 4;
  public static final int BOOLEANO = 38;
  public static final int STRING = 40;
  public static final int INICIO = 23;
  public static final int TER = 3;
  public static final int FLOTANTE = 36;
  public static final int DO = 31;
}

